FROM python:3.11-slim

WORKDIR /app

# Копируем requirements.txt из родительской директории
COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Копируем всю папку backend внутрь /app/
COPY . /app/backend

# Запускаем main.py как часть пакета backend
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
