"""drop unused user columns

Revision ID: 0a187be0f534
Revises: 4853e9167b9e
Create Date: 2025-08-05 12:10:40.393343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0a187be0f534'
down_revision: Union[str, Sequence[str], None] = '4853e9167b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'joined_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'connected')
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', sqlite.JSON(), nullable=True))
    op.add_column('users', sa.Column('connected', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('joined_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
